spring:
  config:
    activate:
      on-profile: test
  datasource:
    password: password
    url: jdbc:h2:dev
    username: SA
name: test-YAML
environment: testing
enabled: false
servers:
  - www.abc.test.com
  - www.xyz.test.com

---
spring:
  config:
    activate:
      on-profile: development
  datasource:
    password: passwd
    url: jdbc:postgresql://localhost:5432/
    username: postgres
name: prod-YAML
environment: production
enabled: true
servers:
  - www.abc.com
  - www.xyz.com